cam0:
  T_cam_imu:
  - [0.7169818381982592, 0.6970538010632054, 0.0072830019348181785, 
      -0.0012536611560942615]
  - [0.006618631659324747, 0.0036401142385785734, -0.9999714712346988, 
      -0.0033330354732342632]
  - [-0.6970604259379551, 0.7170095870988527, -0.002003646557941857, 
      -0.034412271194904816]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [0.7169818381982591, 0.0066186316593247075, -0.6970604259379551, 
      -0.023066520002333755]
  - [0.6970538010632054, 0.003640114238578545, 0.7170095870988529, 
      0.025559930264577056]
  - [0.007283001934818229, -0.9999714712346991, -0.0020036465579418633, 
      -0.003392759997952699]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [-0.0030298331129002282, -0.017101878251559142, -0.9998491615596709, 
      -0.031941009985058916]
  - [0.0046230241962143615, 0.9998428265265162, -0.017115778999151926, 
      -0.00025678243762673975]
  - [0.9999847237626128, -0.0046741848204197144, -0.0029502945065481567, 
      -0.0327539776274321]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.05933995492434185, 0.531696636551898, 
      0.0015047415954313754, 0.0028608011794780857, 0.0]
  intrinsics: [3.232278567501231, 1675.6116033539793, 1675.814846577497, 
      525.9786479571158, 613.7191867928777]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/left/image_raw
cam1:
  T_cam_imu:
  - [0.703900945993541, -0.7096774307060403, 0.02968842494763846, 
      0.0020669203169573977]
  - [0.019137010752290573, -0.022833875592367187, -0.9995560959470455, 
      -0.00334137288534561]
  - [0.7100403038200471, 0.7041566292181776, -0.002491682008086693, 
      -0.034336983207969116]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [0.703900945993541, 0.01913701075229051, 0.7100403038200471, 
      0.022989678711684936]
  - [-0.7096774307060402, -0.022833875592367183, 0.7041566292181772, 
      0.025569164560485434]
  - [0.029688424947638497, -0.9995560959470453, -0.0024916820080866453, 
      -0.003486810088353381]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.010217064421862893, -0.027612023807660077, -0.9995664999067571, 
      -0.032409656273219435]
  - [-0.009475319608608214, 0.9995711227553431, -0.027709003445406197, 
      -0.0009751754564202116]
  - [0.9999029102432468, 0.009754316729941714, 0.0099510498048071, 
      -0.03270849406129646]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.07464895389017981, 0.5959711922306546, 
      -0.0025172532797002913, -0.0003416805901147503, 0.0]
  intrinsics: [3.2103672599557918, 1655.217356499564, 1656.04636834155, 
      543.1108393965394, 601.0581596937154]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/right/image_raw
cam2:
  T_cam_imu:
  - [-0.7164577384832345, -0.697617750879157, 0.004216945078579948, 
      0.0018894901932016706]
  - [-0.00048317047481344355, -0.005548466111916062, -0.999984490414775, 
      -0.0034735581048305196]
  - [0.6976303286940595, -0.7164486640242351, 0.0036381731826637953, 
      -0.030575303565903506]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [-0.7164577384832345, -0.0004831704748133957, 0.6976303286940595, 
      0.02268232062659063]
  - [-0.6976177508791569, -0.00554846611191618, -0.7164486640242351, 
      -0.02060676641246985]
  - [0.004216945078579899, -0.999984490414775, 0.003638173182663677, 
      -0.0033702338582710344]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [-0.009106512366422355, -0.0019966156698819574, -0.9999565415348746, 
      -0.032433849784215145]
  - [-0.02609044747211542, 0.9996580397929443, -0.001758416342299056, 
      -0.00013977967250815442]
  - [0.9996181070705079, 0.026073300581147374, -0.00915549089782508, 
      -0.032868685858232015]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.09159209046997499, 0.770495855233691, 
      -0.0006863992977074038, 0.0027025729754086352, 0.0]
  intrinsics: [3.21551022905022, 1659.9987072352956, 1660.0964283698427, 
      572.4202846819953, 647.790184651347]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/bright/image_raw
cam3:
  T_cam_imu:
  - [-0.6991915146978277, 0.7149035055384614, -0.006648574537226282, 
      -0.001765467372832872]
  - [-0.0023859554576130537, -0.011632822459500702, -0.9999294898432491, 
      -0.0035928296631478184]
  - [-0.7149304392674243, -0.6991263513918247, 0.009839298676375119, 
      -0.030625175075624306]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [-0.6991915146978273, -0.0023859554576129115, -0.714930439267424, 
      -0.02313784200756152]
  - [0.7149035055384612, -0.011632822459500444, -0.6991263513918247, 
      -0.0201905228472037]
  - [-0.006648574537226367, -0.9999294898432487, 0.009839298676375396, 
      -0.0033029839290010547]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.002183759084029801, 0.0030196822429664726, -0.9999930563335997, 
      -0.03233419578367306]
  - [0.0056080519507377136, 0.999979678496041, 0.0030318885652957104, 
      -3.723759214403133e-05]
  - [0.9999818903108098, -0.005614633924492044, 0.002166780171867666, 
      -0.03246788384640441]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.08032763191402349, 0.6031628381941796, 
      -0.001146494003927496, -0.0009644893318249233, 0.0]
  intrinsics: [3.210449269790184, 1661.1757334198858, 1661.514715936475, 
      540.2160466417871, 599.5125388875606]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/bleft/image_raw
